### ISSUE TITLE
Does not work in Sublime 2.0.1 2217 for Windows

### ISSUE THREAD

**Issue by abrkn** [matthiasg/sublime-mocha-runner#2]
![image](https://f.cloud.github.com/assets/843958/448586/ac490006-b24f-11e2-96f4-7b9704d1d2ff.png)

![image](https://f.cloud.github.com/assets/843958/448588/bd48065e-b24f-11e2-8712-13932c95c3f0.png)

Is it possible to output more debugging information?

**Comment by matthiasg** [comment]
it is actuall proving quite difficult to get these kinds of errors into the output. since node.js has a standing issue with flushing stdout/stderr on process exit. mocha (which I start as a process) usually writes out output to stdout/stderr explaining the problem (often a syntactical error in your case) but mocha then calls process.exit() which immediately exists the process, without flushing stdout thus I cannot grab the output. 

Isaac also seems to retain that behavior since process.exit should not need to sync anything, just exit. others like me would like to have an option to flush stdout/stderr before exiting. 

the only way to solve this would be to patch mocha to use a wrapped form of process.exit() which performs correctly. this could be done globally in the main mocha cli js. I will look into it a little more...

I myself actually switched to adding a test.js which configured and runs mocha. maybe I should make that an option too..

**Comment by benediktarnold** [comment]
I have the same behavior on OSX (sublime 2.0.2 build 2221) This issue seems to be not tied to windows.

**Comment by amhed** [comment]
I have the same issue as @benediktarnold running OSX 10.9

**Comment by matthiasg** [comment]
I have been using a different method lately to re-run tests (using cura-test-runner) but I am going to look into this as soon as I can

-matthias

-----Original Message-----

**Comment by amhed** [comment]
I opted to have an open console and start mocha with --watch --growl :sunglasses:

**Comment by matthiasg** [comment]
Watch does not work well with large projects , that's why we dont use it anymore .. nodemon  works better 

Sent from Surface

From: amhed
Sent: ‎Saturday‎, ‎November‎ ‎16‎, ‎2013 ‎08‎:‎34
To: matthiasg/sublime-mocha-runner
Cc: mgt576@gmail.com

I opted to have an open console and start mocha with --watch --growl  :sunglasses:

**Comment by amhed** [comment]
Will give it a try. Thanks

**Comment by matthiasg** [comment]
Too old (switched editor)
